import Head from 'next/head'
//import Image from 'next/image'
import Layout from "../../components/Layout"
import ButtonGoHome from "../../components/ButtonGoHome"
import styles from '@/styles/Evolution.module.scss'

const Evolution:React.FC = () => {
  return (
    <Layout>

      <Head>
        <title>Evolution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.evolution}>

        <h1 className={styles.evolutionmaintitle}>Evolution</h1>

        <ButtonGoHome />

        <div className={styles.articlecontainer}>
          <div className={styles.article}>
            <h3>History</h3>
            <p>blabla</p>
          </div>
          <div className={styles.article}>
            <h3>Motivation</h3>
            <p>blabla</p>
          </div>
          <div className={styles.article}>
            <h3>art 3</h3>
            <p>blabla</p>
          </div>
          <div className={styles.article}>
            <h3>Skills</h3>
            <p>blabla</p>
          </div>
          <div className={styles.article}>
            <h3>Objectifs</h3>
            <p>blabla</p>
          </div>
          <div className={styles.article}>
            <h3>Valeurs</h3>
            <p>blabla</p>
          </div>
        </div>


      </div>


    </Layout>
  )
}
export default Evolution