import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Layout from "../../components/Layout"
import ButtonGoHome from "../../components/ButtonGoHome"
import styles from '@/styles/Evolution.module.scss'

const Evolution:React.FC = () => {
  return (
    <Layout>

      <Head>
        <title>Evolution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.evolution}>

        <h1 className={styles.evolutionmaintitle}>Evolution</h1>

        <ButtonGoHome />

        <div className={styles.mainclassvideo}>
          <video 
            width="100%"
            height="100%"
            autoPlay 
            muted 
            loop 
            className={styles.divvideointro}>
            <source src={"/videos/abstract.mp4"} type="video/mp4"/>
          </video>
        </div>

        <div className={styles.articlecontainer}>

          <div className={styles.article}>
            <h2 className={styles.h2}>Story</h2>
            <p className={styles.p}>
              Mon premier ordinateur était un mac book G3. Seulement, l'information
              n'était pas aussi accessible qu'aujourd'hui. Je me souviens encore des
              pages internet sans mise en forme ni couleurs. J'étais très frustré de
              ne pas comprendre comment fonctionnait mon ordinateur de l'époque.
            </p>
          </div>
          <div className={styles.article2}>
            <h2 className={styles.h2}>Motivation</h2>
            <p className={styles.p}>
              Au fil du temps, j'ai vu ma motivation croître pour l'informatique,
              raison pour laquelle, je souhaiterais faire de ma passion un métier.
            </p>
            <p className={styles.p}>
              J'aime comprendre le fonctionnement des applications, des SI et des 
              communcations internet serveur-client.
            </p>
          </div>
        </div>

        <div className={styles.articlecontainer}>
          <div className={styles.article3}>
            <h2 className={styles.h2}>Personnalité</h2>
            <p className={styles.p}>
              Je suis quelqu'un de rigoureux, structuré et curieux. J'aime me tenir 
              informé sur les nouvelles technologies, la sécurité ainsi que sur les 
              bonnes pratiques.
            </p>
          </div>
          
          <div className={styles.article4}>
            
            <div className={styles.imgevolution}>
              <Image
                src={'/images/super.png'}
                width="1920"
                height="1280"
                alt="img about"
                className={styles.img}
              />
            </div>

            <h2 className={styles.h2}>Skills</h2>
            <div className={styles.lilink}>
              <li className={styles.li}>
                <Link href="/skills" className={styles.linksoft}>
                  Soft Skills
                </Link>
              </li>
              <li className={styles.li}>
                <Link href="/skills" className={styles.linkhard}>
                  Hard Skills
                </Link>
              </li>
            </div>
          
          </div>
        </div>

        <div className={styles.articlecontainer}>
          <div className={styles.article5}>
            <h2 className={styles.h2}>Objectifs</h2>
            <p className={styles.p}>
              Devenir un excellent développeur et travailler avec des pros serait
              pour moi l'idéal. Plusieurs cerveaux valent toujours mieux qu'un ! 
              Aussi, je pense que pour construire et s'enrichir il faut être plusieurs.
            </p>
          </div>
          <div className={styles.article6}>
            <h2 className={styles.h2}>Valeurs</h2>
            <p className={styles.p}>
              Les métiers d'informaticien et d'infirmier ne sont pas si éloignés... 
              Leur point commun: la science. L'une traite des divers systèmes du corps humain,
              l'autre des différents systèmes des système informatique.
            </p>
            <p className={styles.p}>
              Le domaine des soins m'a appris à réfléchir avant, pendant et après l'action.
              Par conséquent, la remise en question fait partie intégrante de ma personne.
              Paramétrer et trouver des solutions sont 2 points essentiels à mes yeux.
            </p>
            <p className={styles.p}>
              Les soins m'ont également permis d'exercer cela. Le fait d'identifier une
              problématique et faire des liens pour résoudre.
            </p>
          </div>
        </div>

        <hr className={styles.hr} />

        <div className={styles.fieldcontainer}>
          <div className={styles.bgfieldset}>
            <fieldset className={styles.field}>
              <legend className={styles.legend}>
                Mon Mojo !
              </legend>
              <label>
                <p className={styles.label}>
                  Le code, les fonctionnalités et apprendre.
                </p>
              </label>
            </fieldset>
          </div>

          <div className={styles.imgevolution}>
            <Image
              src={'/images/super.png'}
              width="200"
              height="200"
              alt="img about"
              className={styles.img}
            />
          </div>
        </div>

      </div>

    </Layout>
  )
}
export default Evolution