import Head from 'next/head'
import Layout from "../../components/Layout"
import ButtonGoHome from "../../components/ButtonGoHome"
import styles from '@/styles/Contact.module.scss'

const Contact:React.FC = () => {
  return (
    <Layout>

      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.contact}>
        
        <div className={styles.maindivvideocontact}>
          <video 
            autoPlay 
            muted 
            loop 
            className={styles.divvideocontact}>
            <source src={"/videos/space.mp4"} type="video/mp4"/>
          </video>
        </div>

        <ButtonGoHome />

        <h1 className={styles.maintitlecontact}>Contact</h1>

        <div className={styles.divcontact}>
          <div className={styles.divh3first}>
            <h3 className={styles.h3}>Cédric Kuchen</h3>
          </div>
          <div className={styles.divh3second}>
            <h3 className={styles.h3}>Software programmer & Web Developer</h3>
          </div>
          <div className={styles.divh3third}>
            <h3 className={styles.h3}>cedric.kuchen@protonmail.com</h3>
          </div>
          <div className={styles.divh3fourth}>
            <h3 className={styles.h3}>079 210 32 30</h3>
          </div>
          <div className={styles.divh3fifth}>
            <h3 className={styles.h3}>Lausanne (Switzerland)</h3>
          </div>
        </div>

      </div>
    </Layout>
  )
}

export default Contact