import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Layout from "../../components/Layout"
import FirstArticle from "../../components/AboutComponent/FirstArticle"
import SecondArticle from "../../components/AboutComponent/SecondArticle"
import ThirdArticle from "../../components/AboutComponent/ThirdArticle"
import FifthArticle from "../../components/AboutComponent/FifthArticle"
import SixthArticle from "../../components/AboutComponent/SixthArticle"
import FieldArticle from "../../components/AboutComponent/FieldArticle"
import ButtonGoHome from "../../components/ButtonGoHome"
import styles from '@/styles/About.module.scss'

const About:React.FC = () => {
  return (
    <Layout>

      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.about}>

        <h1 className={styles.aboutmaintitle}>About Me</h1>

        <ButtonGoHome />

        <div className={styles.mainclassvideo}>
          <video 
            width="100%"
            height="100%"
            autoPlay 
            muted 
            loop 
            className={styles.divvideointro}>
            <source src={"/videos/abstract.mp4"} type="video/mp4"/>
          </video>
        </div>

        <div className={styles.articlecontainer}>

          <FirstArticle />
          <SecondArticle />

        </div>

        <div className={styles.articlecontainer}>

          <ThirdArticle />
          
          <div className={styles.article4}>
            
            <div className={styles.imgabout}>
              <Image
                src={'/images/super.png'}
                width="1920"
                height="1280"
                alt="img about"
                className={styles.img}
              />
            </div>

            <h2 className={styles.h2}>Skills</h2>
            <div className={styles.lilink}>
              <li className={styles.li}>
                <Link href="/skills" className={styles.linksoft}>
                  Soft Skills
                </Link>
              </li>
              <li className={styles.li}>
                <Link href="/skills" className={styles.linkhard}>
                  Hard Skills
                </Link>
              </li>
            </div>
          
          </div>
        </div>

        <div className={styles.articlecontainer}>

          <FifthArticle />
          <SixthArticle />

        </div>

        <hr className={styles.hr} />

        <div className={styles.fieldcontainer}>
          
          <FieldArticle />

          <div className={styles.imgself}>
            <Image
              src={'/images/self.jpg'}
              width="200"
              height="300"
              alt="img about"
              className={styles.img2}
            />
          </div>

        </div>

      </div>

    </Layout>
  )
}
export default About