import { useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Layout from "../components/Layout"
import AnimationIntro from "../components/AnimationIntro"
import VerticalText from "../components/VerticalText"
import { myurls } from "../data/myurls"
import { leftitems } from "../data/leftitems"
import { GoInfo } from 'react-icons/go'
import styles from '@/styles/Home.module.scss'

interface MyurlsItemsProps {
  id: number | null
  name: string
  url: string
}

interface MyurlsProps extends Array<MyurlsItemsProps>{}

interface MyLeftItemsProps {
  id: number | null
  address: string
  name: string
}

interface MyLeftProps extends Array<MyLeftItemsProps>{}

const Home:React.FC = () => {
  const [myurlsCall] = useState<MyurlsItemsProps[]>(myurls)
  const [leftItemsCall] = useState<MyLeftItemsProps[]>(leftitems)
  return (
    <Layout>
      <Head>
        <title>Portfolio NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <main data-testid="firsttesthome" className={styles.main}>
          
          <AnimationIntro />

          <div className={styles.divaudio}>
            <audio
              controls
              loop
              src="/drums.mp3"
              preload="auto"
              className={styles.audio}
            >
              Your browser does not support the
              <code>audio</code> element.
            </audio>
          </div>

          <div className={styles.mainclassvideo}>
            <video
              autoPlay 
              muted 
              loop 
              className={styles.divvideointro}>
              <source
                src={"/videos/spider-web.mp4"}
                type="video/mp4"/>
            </video>
          </div>

          <h2 className={styles.mainheader}>Next.js Portfolio</h2>

          <div className={styles.lilink}>
            {leftItemsCall.map((leftItem: any) => (
              <li key={leftItem.id} className={styles.list}>
                <Link
                  href={leftItem.address}
                  className={styles.link}>
                  <GoInfo
                    size={18}
                    style={{marginRight: "5px", padding: "4px"}} />
                  {leftItem.name}&nbsp;
                </Link>
              </li>
            ))}
          </div>

          <div className={styles.secondlilink}>
            {myurlsCall.map((myurl: any) => (
              <li key={myurl.id} className={styles.list}>
                <a
                  href={`${myurl.url}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className={styles.link2}
                >
                  {myurl.name}
                </a>
              </li>
            ))}
          </div>

          <VerticalText />

        </main>
      </div>
    </Layout>
  )
}
export default Home
